const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const ItemSchema = new Schema({
    id: { type: Number, required: false },
    name: { type: String, required: false },
    itemType: { type: String, required: false },
    itemCategory: { type: String, required: false },
    raid: { type: String, required: false },
    encounters: [{ type: String, required: false }],
    priority: [{
        _id: false,
        classes: [{ type: String, require: false }],
    }],
    deName: { type: String, required: false }
}, { _id: false });

const WishlistSchema = new Schema({
    'locked': { type: Boolean, required: false },
    'bracket-1': {
        itemTypes: [{ type: String, required: false }],
        'slot-1': { item: { type: ItemSchema, default: {} } },
        'slot-2': { item: { type: ItemSchema, default: {} } },
        'slot-3': { item: { type: ItemSchema, default: {} } },
        'slot-4': { item: { type: ItemSchema, default: {} } },
        'slot-5': { item: { type: ItemSchema, default: {} } },
        'slot-6': { item: { type: ItemSchema, default: {} } },
        points: { type: Number, required: false },
    },
    'bracket-2': {
        itemTypes: [{ type: String, required: false }],
        'slot-1': { item: { type: ItemSchema, default: {} } },
        'slot-2': { item: { type: ItemSchema, default: {} } },
        'slot-3': { item: { type: ItemSchema, default: {} } },
        'slot-4': { item: { type: ItemSchema, default: {} } },
        'slot-5': { item: { type: ItemSchema, default: {} } },
        'slot-6': { item: { type: ItemSchema, default: {} } },
        points: { type: Number, required: false },
    },
    'bracket-3': {
        itemTypes: [{ type: String, required: false }],
        'slot-1': { item: { type: ItemSchema, default: {} } },
        'slot-2': { item: { type: ItemSchema, default: {} } },
        'slot-3': { item: { type: ItemSchema, default: {} } },
        'slot-4': { item: { type: ItemSchema, default: {} } },
        'slot-5': { item: { type: ItemSchema, default: {} } },
        'slot-6': { item: { type: ItemSchema, default: {} } },
        points: { type: Number, required: false },
    },
    'bracket-4': {
        itemTypes: [{ type: String, required: false }],
        'slot-1': { item: { type: ItemSchema, default: {} } },
        'slot-2': { item: { type: ItemSchema, default: {} } },
        'slot-3': { item: { type: ItemSchema, default: {} } },
        'slot-4': { item: { type: ItemSchema, default: {} } },
        'slot-5': { item: { type: ItemSchema, default: {} } },
        'slot-6': { item: { type: ItemSchema, default: {} } },
        points: { type: Number, required: false },
    },
    'bracketless': {
        'slot-1': { item: { type: ItemSchema, default: {} } },
        'slot-2': { item: { type: ItemSchema, default: {} } },
        'slot-3': { item: { type: ItemSchema, default: {} } },
        'slot-4': { item: { type: ItemSchema, default: {} } },
        'slot-5': { item: { type: ItemSchema, default: {} } },
        'slot-6': { item: { type: ItemSchema, default: {} } },
        'slot-7': { item: { type: ItemSchema, default: {} } },
        'slot-8': { item: { type: ItemSchema, default: {} } },
        'slot-9': { item: { type: ItemSchema, default: {} } },
        'slot-10': { item: { type: ItemSchema, default: {} } },
        'slot-11': { item: { type: ItemSchema, default: {} } },
        'slot-12': { item: { type: ItemSchema, default: {} } },
        'slot-13': { item: { type: ItemSchema, default: {} } },
        'slot-14': { item: { type: ItemSchema, default: {} } },
        'slot-15': { item: { type: ItemSchema, default: {} } },
        'slot-16': { item: { type: ItemSchema, default: {} } },
        'slot-17': { item: { type: ItemSchema, default: {} } },
        'slot-18': { item: { type: ItemSchema, default: {} } },
        'slot-19': { item: { type: ItemSchema, default: {} } },
        'slot-20': { item: { type: ItemSchema, default: {} } },
        'slot-21': { item: { type: ItemSchema, default: {} } },
        'slot-22': { item: { type: ItemSchema, default: {} } },
        'slot-23': { item: { type: ItemSchema, default: {} } },
        'slot-24': { item: { type: ItemSchema, default: {} } },
        'slot-25': { item: { type: ItemSchema, default: {} } },
        'slot-26': { item: { type: ItemSchema, default: {} } },
        'slot-27': { item: { type: ItemSchema, default: {} } },
        'slot-28': { item: { type: ItemSchema, default: {} } },
        'slot-29': { item: { type: ItemSchema, default: {} } },
        'slot-30': { item: { type: ItemSchema, default: {} } },
        'slot-31': { item: { type: ItemSchema, default: {} } },
        'slot-32': { item: { type: ItemSchema, default: {} } },
    },
    filterList: [{ type: Number, required: false }],
}, { _id: false });

const PlayerSchema = new Schema({
    discordId: { type: Number, required: false },
    name: { type: String, required: false },
    class: { type: String, required: false },
    race: { type: String, required: false },
    role: { type: String, required: false },
    permissions: { type: String, required: false },
    aq_attendance: { type: Number, required: false },
    naxx_attendance: { type: Number, required: false },
    wishlist: WishlistSchema,
});

module.exports = mongoose.model('Player', PlayerSchema);
