const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const ItemSchema = new mongoose.Schema({
    id: { type: Number, required: false },
    name: { type: String, required: false },
    itemType: { type: String, required: false },
    itemCategory: { type: String, required: false },
    raid: { type: String, required: false },
    encounters: [{ type: String, required: false }],
    priority: [{
        _id: false,
        classes: [{ type: String, require: false }],
    }],
    deName: { type: String, required: false }
}, { _id: false });

const WishlistSchema = new Schema({
    'locked': { type: Boolean, required: false },
    'bracket-1': {
        itemTypes: [{ type: String, required: false }],
        'slot-1': { type: ItemSchema, default: null },
        'slot-2': { type: ItemSchema, default: null },
        'slot-3': { type: ItemSchema, default: null },
        'slot-4': { type: ItemSchema, default: null },
        'slot-5': { type: ItemSchema, default: null },
        'slot-6': { type: ItemSchema, default: null },
        points: { type: Number, required: false },
    },
    'bracket-2': {
        itemTypes: [{ type: String, required: false }],
        'slot-1': { type: ItemSchema, default: null },
        'slot-2': { type: ItemSchema, default: null },
        'slot-3': { type: ItemSchema, default: null },
        'slot-4': { type: ItemSchema, default: null },
        'slot-5': { type: ItemSchema, default: null },
        'slot-6': { type: ItemSchema, default: null },
        points: { type: Number, required: false },
    },
    'bracket-3': {
        itemTypes: [{ type: String, required: false }],
        'slot-1': { type: ItemSchema, default: null },
        'slot-2': { type: ItemSchema, default: null },
        'slot-3': { type: ItemSchema, default: null },
        'slot-4': { type: ItemSchema, default: null },
        'slot-5': { type: ItemSchema, default: null },
        'slot-6': { type: ItemSchema, default: null },
        points: { type: Number, required: false },
    },
    'bracket-4': {
        itemTypes: [{ type: String, required: false }],
        'slot-1': { type: ItemSchema, default: null },
        'slot-2': { type: ItemSchema, default: null },
        'slot-3': { type: ItemSchema, default: null },
        'slot-4': { type: ItemSchema, default: null },
        'slot-5': { type: ItemSchema, default: null },
        'slot-6': { type: ItemSchema, default: null },
        points: { type: Number, required: false },
    },
    'bracketless': {
        'slot-1': { type: ItemSchema, default: null },
        'slot-2': { type: ItemSchema, default: null },
        'slot-3': { type: ItemSchema, default: null },
        'slot-4': { type: ItemSchema, default: null },
        'slot-5': { type: ItemSchema, default: null },
        'slot-6': { type: ItemSchema, default: null },
        'slot-7': { type: ItemSchema, default: null },
        'slot-8': { type: ItemSchema, default: null },
        'slot-9': { type: ItemSchema, default: null },
        'slot-10': { type: ItemSchema, default: null },
        'slot-11': { type: ItemSchema, default: null },
        'slot-12': { type: ItemSchema, default: null },
        'slot-13': { type: ItemSchema, default: null },
        'slot-14': { type: ItemSchema, default: null },
        'slot-15': { type: ItemSchema, default: null },
        'slot-16': { type: ItemSchema, default: null },
        'slot-17': { type: ItemSchema, default: null },
        'slot-18': { type: ItemSchema, default: null },
        'slot-19': { type: ItemSchema, default: null },
        'slot-20': { type: ItemSchema, default: null },
        'slot-21': { type: ItemSchema, default: null },
        'slot-22': { type: ItemSchema, default: null },
        'slot-23': { type: ItemSchema, default: null },
        'slot-24': { type: ItemSchema, default: null },
        'slot-25': { type: ItemSchema, default: null },
        'slot-26': { type: ItemSchema, default: null },
        'slot-27': { type: ItemSchema, default: null },
        'slot-28': { type: ItemSchema, default: null },
        'slot-29': { type: ItemSchema, default: null },
        'slot-30': { type: ItemSchema, default: null },
        'slot-31': { type: ItemSchema, default: null },
        'slot-32': { type: ItemSchema, default: null },
    },
    filterList: [{ type: String, required: false }],
}, { _id: false });
const PlayerSchema = new Schema({
    discordId: { type: Number, required: false },
    name: { type: String, required: false },
    class: { type: String, required: false },
    race: { type: String, required: false },
    role: { type: String, required: false },
    permissions: { type: String, required: false },
    aq_attendance: { type: Number, required: false },
    naxx_attendance: { type: Number, required: false },
    wishlist: WishlistSchema,
});

module.exports = mongoose.model('Player', PlayerSchema);
